import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Auto-generated from the docs/ folder structure, so adding a new page
// doesn't also require a manual sidebar edit.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
